#include "BMI088.h"
#include <Dynamixel2Arduino.h>
#include <FastLED.h>
#include <array>
#include "complementary_filter.h"
#include <Preferences.h>
#include "fast_slave.h"


#define DEBUG true
#define DEBUG_SERIAL Serial

#define DXL_DIR_PIN 15
#define DXL_U2_RX_PIN 16
#define DXL_U2_TX_PIN 17

#define DXL_PROTOCOL_VER_2_0 2.0
#define DXL_MODEL_NUM 0xbaff
#define DEFAULT_ID 241
#define DEFAULT_BAUD 4 //2mbaud

#define ADDR_CONTROL_ITEM_BAUD 8

#define ADDR_CONTROL_ITEM_LED0_R 10
#define ADDR_CONTROL_ITEM_LED0_G 11
#define ADDR_CONTROL_ITEM_LED0_B 12
#define ADDR_CONTROL_ITEM_LED1_R 14
#define ADDR_CONTROL_ITEM_LED1_G 15
#define ADDR_CONTROL_ITEM_LED1_B 16
#define ADDR_CONTROL_ITEM_LED2_R 18
#define ADDR_CONTROL_ITEM_LED2_G 19
#define ADDR_CONTROL_ITEM_LED2_B 20

#define ADDR_CONTROL_ITEM_GYRO_X 36
#define ADDR_CONTROL_ITEM_GYRO_Y 40
#define ADDR_CONTROL_ITEM_GYRO_Z 44
#define ADDR_CONTROL_ITEM_ACCEL_X 48
#define ADDR_CONTROL_ITEM_ACCEL_Y 52
#define ADDR_CONTROL_ITEM_ACCEL_Z 56
#define ADDR_CONTROL_ITEM_QUAT_X 60
#define ADDR_CONTROL_ITEM_QUAT_Y 64
#define ADDR_CONTROL_ITEM_QUAT_Z 68
#define ADDR_CONTROL_ITEM_QUAT_W 72

#define ADDR_CONTROL_ITEM_BUTTON0 76
#define ADDR_CONTROL_ITEM_BUTTON1 77
#define ADDR_CONTROL_ITEM_BUTTON2 78

#define ADDR_CONTROL_ITEM_GYRO_RANGE 102
#define ADDR_CONTROL_ITEM_ACCEL_RANGE 103
#define ADDR_CONTROL_ITEM_CALIBRATE_GYRO 104
#define ADDR_CONTROL_ITEM_RESET_GYRO_CALIBRATION 105
#define ADDR_CONTROL_ITEM_CALIBRATE_ACCEL 106
#define ADDR_CONTROL_ITEM_RESET_ACCEL_CALIBRATION 107

#define ADDR_CONTROL_ITEM_DO_ADAPTIVE_GAIN 108
#define ADDR_CONTROL_ITEM_DO_BIAS_ESTIMATION 109
#define ADDR_CONTROL_ITEM_ACCEL_GAIN 110
#define ADDR_CONTROL_ITEM_BIAS_ALPHA 114

#define ADDR_CONTROL_ITEM_ACCEL_CALIBRATION_THRESHOLD 118
#define ADDR_CONTROL_ITEM_ACCEL_BIAS_X 122
#define ADDR_CONTROL_ITEM_ACCEL_BIAS_Y 126
#define ADDR_CONTROL_ITEM_ACCEL_BIAS_Z 130
#define ADDR_CONTROL_ITEM_ACCEL_SCALE_X 134
#define ADDR_CONTROL_ITEM_ACCEL_SCALE_Y 138
#define ADDR_CONTROL_ITEM_ACCEL_SCALE_Z 142



#define ACCEL_CS 12
#define GYRO_CS 5

// default parameters for BMI088
#define ACCEL_RANGE_DEFAULT Bmi088Accel::RANGE_12G
#define ACCEL_ODR_DEFAULT Bmi088Accel::ODR_100HZ_BW_10HZ
#define GYRO_RANGE_DEFAULT Bmi088Gyro::RANGE_500DPS
#define GYRO_ODR_DEFAULT Bmi088Gyro::ODR_100HZ_BW_12HZ

// default parameters for complementary filter
#define IMU_GAIN_ACCEL_DEFAULT 0.04
#define IMU_DO_ADAPTIVE_GAIN_DEFAULT false
#define IMU_DO_BIAS_ESTIMATION_DEFAULT false
#define IMU_BIAS_ALPHA_DEFAULT 0.01

#define LED_PIN 4
#define NUM_LEDS 3

#define BUTTON0_PIN 27
#define BUTTON1_PIN 14
#define BUTTON2_PIN 12


void setAccelRange(uint8_t range);
void setGyroRange(uint8_t range);