[package]
edition = "2021"
name    = "bitbots_imu_firmware"
version = "0.1.0"

[[bin]]
name = "bitbots_imu_firmware"
path = "./src/main.rs"

[dependencies]
critical-section = "1.2.0"
esp-alloc = { version = "0.6.0" }
esp-backtrace = { version = "0.15.0", features = [
  "esp32",
  "exception-handler",
  "panic-handler",
  "println",
] }
esp-hal = { version = "0.23.1", features = ["esp32", "unstable"] }
esp-println = { version = "0.13.0", features = ["esp32", "log"] }
log = { version = "0.4.21" }
dynamixel2 = { git = "https://github.com/omelia-iliffe/dynamixel2-rs.git", branch = "no_std_example", default-features = false }
embedded-io = "0.6.1"
defmt = "0.3.10"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
